import Navbar from "../../components/Navbar";
import "./globals.css";
// import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";


// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: "400", // if single weight, otherwise you use array like [400, 500, 700],
  style: "normal",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
